// This file will be auto-generated by Laravel Wayfinder
// For now, we'll use placeholder route functions

export const home = () => '/';
export const login = () => '/login';
export const register = () => '/register';
export const dashboard = () => '/dashboard';

export const about = {
    index: () => '/about',
    objectives: () => '/about/objectives',
};

export const services = () => '/services';
export const howItWorks = () => '/how-it-works';
export const faq = () => '/faq';
export const privacy = () => '/privacy';
export const terms = () => '/terms';
export const contact = () => '/contact';
export const announcements = () => '/announcements';
